### ISSUE TITLE
Service Unavailable issue

### ISSUE THREAD

**Issue by suryarend** [georgestephanis/two-factor#217] opened 2018-02-21 04:46 UTC
Upon enabling the plugin for a site, I am getting-

---
Service Unavailable
The service is temporarily unavailable. Please try again later.
---

while trying to access <siteurl>/wp-login.php?action=validate_2fa.  This is true for both Google Authenticator and email auth.

**Comment by ericmann** [comment] 2018-02-21 16:46
Do you have any error logs from the server to help identify the issue?

**Comment by suryarend** [comment] 2018-02-23 01:26
[Thu Feb 22 22:43:58.393813 2018] [:error] [pid 22389] [client 131.107.174.214:13167] PHP Fatal error: Call to a member function get_setting() on string in /nas/content/live/vscom2fa/wp-admin/custom-header.php on line 1339, referer: _<site-url>_%2Fwp-admin%2F&reauth=1

Upon looking at the code I see

/**
	 * Updates the last-used postmeta on a header image attachment after saving a new header image via the Customizer.
	 *
	 * @since 3.9.0
	 *
	 * @param WP_Customize_Manager $wp_customize Customize manager.
	 */
	public function customize_set_last_used( $wp_customize ) {

		**$header_image_data_setting = $wp_customize->get_setting( 'header_image_data' );**
		if ( ! $header_image_data_setting ) {
			return;
		}
		$data = $header_image_data_setting->post_value();

		if ( ! isset( $data['attachment_id'] ) ) {
			return;
		}

		$attachment_id = $data['attachment_id'];
		$key = '_wp_attachment_custom_header_last_used_' . get_stylesheet();
		update_post_meta( $attachment_id, $key, time() );
	}

The bolded line is what failing..

**Comment by nathanlabrake** [comment] 2018-02-26 20:56
Hello Eric,
When you say what other systems we have installed, do you mean what types of plugins?

**Here are some of the errors we're getting in our error logs:**

PHP Warning: include_once(/nas/content/live/testsite/wp-content/plugins/two-factor/providers/class.two-factor-fido-u2f.php): failed to open stream: No such file or directory in /nas/content/live/testsite/wp-content/plugins/two-factor/class.two-factor-core.php on line 100

PHP Warning: include_once(): Failed opening '/nas/content/live/testsite/wp-content/plugins/two-factor/providers/class.two-factor-fido-u2f.php' for inclusion (include_path='.:/usr/share/pear/php:/usr/share/php:/usr/share/pear') in /nas/content/live/testsite/wp-content/plugins/two-factor/class.two-factor-core.php on line 100

PHP Warning: include_once(/nas/content/live/testsite/wp-content/plugins/two-factor/providers/class.two-factor-backup-codes.php): failed to open stream: No such file or directory in /nas/content/live/testsite/wp-content/plugins/two-factor/class.two-factor-core.php on line 100

PHP Warning: include_once(): Failed opening '/nas/content/live/testsite/wp-content/plugins/two-factor/providers/class.two-factor-backup-codes.php' for inclusion (include_path='.:/usr/share/pear/php:/usr/share/php:/usr/share/pear') in /nas/content/live/testsite/wp-content/plugins/two-factor/class.two-factor-core.php on line 100

PHP Warning: include_once(/nas/content/live/testsite/wp-content/plugins/two-factor/providers/class.two-factor-dummy.php): failed to open stream: No such file or directory in /nas/content/live/testsite/wp-content/plugins/two-factor/class.two-factor-core.php on line 100

PHP Warning: include_once(): Failed opening '/nas/content/live/testsite/wp-content/plugins/two-factor/providers/class.two-factor-dummy.php' for inclusion (include_path='.:/usr/share/pear/php:/usr/share/php:/usr/share/pear') in /nas/content/live/testsite/wp-content/plugins/two-factor/class.two-factor-core.php on line 100

PHP Warning: fread() expects parameter 1 to be resource, boolean given in /nas/content/live/testsite/wp-includes/functions.php on line 4837

PHP Warning: fclose() expects parameter 1 to be resource, boolean given in /nas/content/live/testsite/wp-includes/functions.php on line 4840

PHP Warning: fopen(/nas/content/live/testsite/wp-content/plugins/two-factor/two-factor.php): failed to open stream: No such file or directory in /nas/content/live/testsite/wp-includes/functions.php on line 4834

Not totally sure if they are related to the 500 error we're getting above, but I'm assuming it is. Has this plugin been tested for PHP versions older than PHP 7.0, such as PHP 5.6?

Thanks,
Nathan

**Comment by sdellenb** [comment] 2018-02-26 21:06
> Has this plugin been tested for PHP versions older than PHP 7.0, such as PHP 5.6?

I'm running my Wordpress on PHP 5.6.33 and have no issues with the plugin.

Your error messages sound like either files are missing or inaccessible, or some PHP functionality is restricted.

**Comment by ericmann** [comment] 2018-02-26 21:07
Yes, I meant what other plugins. As for those errors ... I _highly_ suspect they're related to the 500 error. The warnings are alerting you that the PHP engine isn't able to even load the files for the plugin. I'd suggest resolving those warnings first as they show something is seriously wrong with your site ...

**Comment by nathanlabrake** [comment] 2018-02-26 23:01
Yes it's possible it deals with the PHP settings, or perhaps the fact that the site is setup as a multisite? I tested this plugin in a clone of this site setup inside a local environment, which isn't setup as a multisite, and for some reason it actually works. I don't know if that would have anything to do with it (I think it wouldn't) but this test shows that it's definitely something with the site configuration. Any ideas where I might look to find out what settings those might be?

Thanks for getting back so promptly.

**Comment by kasparsd** [comment] 2018-06-19 17:14
Please re-open if the issue is still present.

**Closed by kasparsd** 2018-06-19 17:14 UTC
Labels: Integrations
