### ISSUE TITLE
Wordpress mobile app integration

### ISSUE THREAD

**Issue by nthdegreeburns** [georgestephanis/two-factor#190] opened 2017-08-13 16:26 UTC
The plugin works well out of the box. I did try and use it with the official Wordpress mobile app (iOS), and the TFA dialogue wasn't presented to me until after I logged in and tried to preview a post. Then the TFA dialogue from your plugin appeared and basically blocked the preview action. I couldn't get the TFA code to work.

**Comment by kasparsd** [comment] 2017-09-24 07:33
@nthdegreeburns Thanks for reporting the issue! Could this be a duplicate of #122?

**Comment by nthdegreeburns** [comment] 2017-09-25 20:52
It sounds vaguely similar, yes. I would suspect this would be a closed issue if the bug fix was in 2 days ago and then wait for it to come back up again. I'm not using the mobile app for another reason right now -- it just is very limited in its capabilities.

**Comment by kasparsd** [comment] 2017-09-26 07:51
Thanks @nthdegreeburns! I'll close this out for now. Feel free to re-open if this pops up again.

**Closed by kasparsd** 2017-09-26 07:51 UTC
