### ISSUE TITLE
Cannot register Yubikey with Chrome

### ISSUE THREAD

**Issue by norbusan** [georgestephanis/two-factor#116] opened 2016-03-19 08:02 UTC
Hi,

I am trying to register my yubikey neo with the plugin, but then clicking on "New" it an instant it changes to "Failed" without me doing anything.

I am running chrome 49, and verified on the yubico test site that the key can be used with this browser.

OS is Debian/unstable.

Thanks

**Comment by kasparsd** [comment] 2016-03-19 08:05
U2F requires an HTTPS connection. Do you have that?

**Comment by lazyrivr** [comment] 2016-03-20 07:35
I've gotten the same thing on a couple of my Wordpress sites (though not all), and all of them have HTTPS. I'm running Chrome 49 on Windows 10.

All the sites I'm having trouble with have been around for a while, and have/had several plugins, so I think it might be some kind of plugin conflict. Interestingly, they have all had other two-factor plugins previously as well - either [Google Authenticator](https://wordpress.org/plugins/google-authenticator/) or [Authy](https://wordpress.org/plugins/authy-two-factor-authentication/) - so maybe it's related somehow.

**Comment by lazyrivr** [comment] 2016-03-20 08:05
I retract my previous theory - it turns out the answer is much simpler than that (at least for my situation).

I noticed closed issue #89  that was very similar, and, based on the comments there, checked out the console. That's when I noticed it:

> sign Object {version: "U2F_V2", challenge: "rw1XSYbsNrMP8l6B-P6khCKb7acUQsyuTP0lUdqeA8c", appId: "**_http_**://www.andy-bell.com"}
> Register callback Object {errorCode: 2} Window {external: Object, chrome: Object, document: document, ajaxurl: "/wp-admin/admin-ajax.php", pagenow: "profile"…}
> Registration Failed 2

The appId was just http, not https. Back when I converted all my sites to HTTPS, I did so with server redirects. In doing so, I forgot to go to the General Settings in WordPress and change the WordPress Address and Site Address URLs to http**s**.

I went in, changed those settings, and tried adding the U2F key again, and it worked - on all 4 sites that it wasn't working on before. WordPress in general had been working fine with just the server redirects for over a year, but that little oversight seems to be what caused U2F to fail.

**Comment by norbusan** [comment] 2016-03-20 09:58
Bingo!
I can confirm that. But I still consider it a bug.
I think it is quite common to have the main site on http, but use admin only over https.

Thanks for your research!

Norbert

**Comment by norbusan** [comment] 2016-03-20 10:50
One more thing: After changing the http to https, and unconditionally returning true in `providers/class.two-factor-fido-u2f.php`, function `is_browser_support`, I can use the yubikey also with firefox and the u2f addon: https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/

So it would be nice if this would be supported from the plugin out of the box.

**Comment by kasparsd** [comment] 2016-03-20 11:25
Thanks for confirming the HTTPS issue @norbusan!

Closing as a duplicate of #79.

**Closed by kasparsd** 2016-03-20 11:25 UTC
Labels: FIDO U2F

**Comment by norbusan** [comment] 2016-03-20 11:39
Thanks - any chance on the firefox extension plugin support?

**Comment by kasparsd** [comment] 2016-03-20 11:40
@norbusan Sure, I created a new issue for that #117.

**Comment by norbusan** [comment] 2016-03-20 11:52
Thanks!
