### ISSUE TITLE
Possible to by-pass two-factor authentication with xmlrpc

### ISSUE THREAD

**Issue by ljb** [georgestephanis/two-factor#212] opened 2018-01-28 22:00 UTC
Two-factor authentication works great in the browser with my YubiKey. However, it seems that XML-RPC can be used to by-pass the two-factor authentication. Example with the Python Wordpress XML-RPC API:

```
from wordpress_xmlrpc import Client
from wordpress_xmlrpc.methods.posts import GetPosts

wp = Client('http://mysite.example.com/xmlrpc.php', 'my-non-admin-user', 'my-ordinary-wordpress-password')
wp.call(GetPosts())
```
This returns a list of posts. The expected behaviour is that a InvalidCredentialsError should be thrown.

I tried installing the application-passwords plugin as well. With that I can use both my ordinary WordPress password, and the application password. The expected behaviour is that I should only be able to use application passwords, and that all other passwords should throw InvalidCredentialsError.

I use the latest stable versions of two-factor, application-passwords and WordPress. My site is self-hosted (not on wordpress.com), and it is a multi site if that matters.

**Comment by kasparsd** [comment] 2019-03-19 11:35
This needs to be fixed. Closing as duplicate of #87.

**Closed by kasparsd** 2019-03-19 11:35 UTC
Labels: Application Passwords
