### ISSUE TITLE
WP 4.8 No email with code

### ISSUE THREAD

**Issue by pwallner** [georgestephanis/two-factor#187] opened 2017-07-27 20:29 UTC
Today I updated to WP 4.8, during login when I use send email code, no email is arriving... U2F is working...

**Comment by nickmomrik** [comment] 2017-08-11 18:23
Ran into this today as well. Seems related to #177. I was able to go into the usermeta table and delete everything with the meta_value = '_two_factor_email_token' to get users working again.

**Comment by kasparsd** [comment] 2017-09-24 07:32
Indeed, this is a duplicate of #177.

**Closed by kasparsd** 2017-09-24 07:32 UTC
Labels: duplicate
